version: "3"

networks:
  strimr:
    external: true

services:
  track-manager:
    build: .
    ports:
    - 8081:8080
    - 5006:5005
    networks:
      - strimr
    environment:
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=track-manager:5005
